import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { AddToCart } from '../../../components/add-to-cart';
import { ProductCard } from '../../../components/product-card';
import { ProductGallery } from '../../../components/product-gallery';
import { formatMoney, getProduct, getProducts, previewProducts } from '../../../lib/commerce';

export async function generateStaticParams() { return previewProducts().map((product) => ({ handle: product.handle })); }
export async function generateMetadata({ params }: { params: Promise<{ handle: string }> }): Promise<Metadata> { const { handle } = await params; const product = await getProduct(handle); if (!product) return {}; const description = product.description.slice(0, 155); const image = product.images[0]?.url; return { title: product.seoTitle, description, alternates: { canonical: `/product-page/${product.handle}` }, openGraph: { title: product.seoTitle, description, images: image ? [image] : [] }, twitter: { card: 'summary_large_image', title: product.seoTitle, description, images: image ? [image] : [] } }; }

export default async function ProductPage({ params }: { params: Promise<{ handle: string }> }) {
  const { handle } = await params; const product = await getProduct(handle); if (!product) notFound();
  const all = await getProducts(); const related = all.filter((item) => item.handle !== product.handle && item.collections.some((collection) => product.collections.includes(collection))).slice(0, 4);
  const structured = { '@context': 'https://schema.org', '@type': 'Product', name: product.title, image: product.images.map((image) => image.url), description: product.description, sku: product.handle, brand: { '@type': 'Brand', name: 'Bioloark' }, offers: { '@type': 'Offer', priceCurrency: product.price.currencyCode, price: product.price.amount, availability: product.availableForSale ? 'https://schema.org/InStock' : 'https://schema.org/OutOfStock', url: `https://www.bioloark.co.il/product-page/${encodeURIComponent(product.handle)}` } };
  return <main className="internal-page product-page"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structured) }} /><div className="breadcrumbs product-breadcrumbs"><a href="/">בית</a><span>/</span><a href="/category/all-products">חנות</a><span>/</span><span>{product.title}</span></div><section className="product-layout"><ProductGallery images={product.images} title={product.title} /><div className="product-info"><p className="eyebrow dark">BIOLOARK LIVING COLLECTION</p><h1>{product.title}</h1><p className="product-price">{formatMoney(product.price)}</p>{product.source === 'preview' && <p className="preview-label">תצוגה מקדימה מתוכן האתר הישן</p>}<div className="product-intro">{product.description.split(/\r?\n\r?\n/)[0] || 'פרטי המוצר יעודכנו דרך Shopify.'}</div><AddToCart variants={product.variants} available={product.availableForSale} title={product.title} handle={product.handle} image={product.images[0]} /><ul className="product-promises"><li>איסוף מהסטודיו בתל אביב</li><li>אריזה מוקפדת המותאמת למוצר חי</li><li>ליווי מקצועי והנחיות טיפול</li></ul></div></section>{product.descriptionHtml && <section className="product-description"><p className="eyebrow dark">DETAILS & CARE</p><h2>פרטים וטיפול</h2><div dangerouslySetInnerHTML={{ __html: product.descriptionHtml }} /></section>}{related.length > 0 && <section className="related-section"><div className="section-heading"><div><p className="eyebrow dark">YOU MAY ALSO LIKE</p><h2>עוד מהעולם שלנו</h2></div></div><div className="product-grid">{related.map((item) => <ProductCard key={item.id} product={item} />)}</div></section>}</main>;
}
